In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.Session()

In [2]:
x = tf.placeholder(tf.float32, shape=(4, 4))

In [3]:
rand_array = np.random.rand(4, 4)
y = tf.identity(x)
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.47038963  0.75609803  0.57779324  0.35853156]
 [ 0.05537965  0.99992335  0.12827754  0.88513023]
 [ 0.34922081  0.5502342   0.40352494  0.04465419]
 [ 0.39250633  0.14713989  0.54669446  0.42578322]]


In [4]:
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./logs", sess.graph)