In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.Session()

In [2]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [3]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-1.23512709 -0.13297431  0.66024154]
 [-0.33054152  0.95160025  0.17803784]]


In [4]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [5]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.55310178  0.0916388 ]
 [ 0.19060719  0.84245241]
 [ 0.46143281  0.68853414]]


In [6]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [7]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 5.4618988   6.03414059  5.10364628]
 [ 3.45344424  5.79395103  5.26341438]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [9]:
print(sess.run(tf.transpose(C)))
print(sess.run(tf.matrix_determinant(D)))
print(sess.run(tf.matrix_inverse(D)))

[[ 0.75782907  0.57421315  0.06211352]
 [ 0.20882738  0.18906462  0.21972477]]
-38.0
[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [10]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
